export const TOKEN_TYPES = {
  SEMICOLON: "SEMICOLON",
  COLON: "COLON",
  COMMA: "COMMA",
  LEFT_PARENTHESES: "LEFT_PARENTHESES",
  RIGHT_PARENTHESES: "RIGHT_PARENTHESES",
  LEFT_CURLY_BRACE: "LEFT_CURLY_BRACE",
  RIGHT_CURLY_BRACE: "RIGHT_CURLY_BRACE",
  ASTERISK: "ASTERISK",
  UNDERSCORE: "UNDERSCORE",
  ARROW: "ARROW",
  REQUEST: "REQUEST",
  RESPONSE: "RESPONSE",
  ERROR: "ERROR",
  ACTOR: "ACTOR",
  INT: "INT",
  STRING: "STRING",
  BOOLEAN: "BOOLEAN",
  IDENTIFIER: "IDENTIFIER",
} as const;

export type TokenType = (typeof TOKEN_TYPES)[keyof typeof TOKEN_TYPES];
